---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-deployment
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: docker.io/androzo/hello-app-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: hello-app-configmap
              key: flask_env
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: hello-app-configmap
              key: flask_app
        - name: MY_VAR
          valueFrom:
            configMapKeyRef:
              name: hello-app-configmap
              key: my_var
        